name: Badminton Court Monitor
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    name: Check Court Availability
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run court monitoring
        run: npm start
        
      - name: Send Test Notification
        run: |
          echo "Sending test notification..."
          curl -H "Content-Type: application/json" \
               -X POST "https://exp.host/--/api/v2/push/send" \
               -d '{
                 "to": "${{ secrets.EXPO_PUSH_TOKEN }}",
                 "title": "🏸 Court Monitor Active",
                 "body": "GitHub Actions is monitoring courts every 5 minutes. Last check: $(date)",
                 "data": { "source": "github_actions" },
                 "sound": "default"
               }'
        
      - name: Log completion
        run: echo "Monitoring cycle completed at $(date)"
