name: Badminton Court Monitor
on:
  schedule:
    # Run every 5 minutes
    - cron: '*/10 * * * *'
  # Also run manually for testing
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    name: Check Court Availability
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Install required dependencies
        run: |
          echo "=== INSTALLING DEPENDENCIES ==="
          npm install node-fetch
          echo "=== DEPENDENCIES INSTALLED ==="
        
      - name: Debug - Check files and environment
        run: |
          echo "=== DEBUGGING ENVIRONMENT ==="
          echo "Current directory: $(pwd)"
          echo "Files in current directory:"
          ls -la
          echo "Node.js version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "=== END DEBUG ==="
        
      - name: Test script syntax
        run: |
          echo "=== TESTING SCRIPT SYNTAX ==="
          if [ -f "monitor-courts-enhanced.js" ]; then
            echo "✅ File exists"
            echo "File size: $(wc -l < monitor-courts-enhanced.js) lines"
            echo "Testing syntax:"
            node -c monitor-courts-enhanced.js && echo "✅ Syntax check passed" || echo "❌ Syntax check failed"
          else
            echo "❌ File not found"
          fi
          echo "=== END SYNTAX TEST ==="
        
      - name: Run enhanced court monitoring
        id: monitor
        run: |
          echo "=== STARTING ENHANCED MONITORING ==="
          echo "Time: $(date)"
          
          # Run enhanced monitoring script
          if [ -f "monitor-courts-enhanced.js" ]; then
            echo "✅ Script file found, running..."
            
            # Run the script and capture output
            OUTPUT=$(node monitor-courts-enhanced.js 2>&1)
            EXIT_CODE=$?
            
            echo "Script exit code: $EXIT_CODE"
            echo "Script output:"
            echo "$OUTPUT"
            
            if [ $EXIT_CODE -eq 0 ]; then
              echo "✅ Script executed successfully"
              
              # Check if changes were detected
              if echo "$OUTPUT" | grep -q "=== CHANGES_DETECTED ==="; then
                echo "changes_detected=true" >> $GITHUB_OUTPUT
                echo "✅ Changes detected!"
              else
                echo "changes_detected=false" >> $GITHUB_OUTPUT
                echo "✅ No changes detected"
              fi
            else
              echo "❌ Script failed with exit code $EXIT_CODE"
              echo "changes_detected=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "❌ Script file not found!"
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi
          
          echo "=== ENHANCED MONITORING COMPLETED ==="
        
      - name: Send Test Notification
        if: steps.monitor.outputs.changes_detected == 'true'
        run: |
          echo "=== SENDING NOTIFICATION ==="
          echo "Time: $(date)"
          
          # Send simple notification for now
          curl -H "Content-Type: application/json" \
               -X POST "https://exp.host/--/api/v2/push/send" \
               -d '{
                 "to": "${{ secrets.EXPO_PUSH_TOKEN }}",
                 "title": "🏸 Court Available!",
                 "body": "New courts available. Check the GitHub Actions logs for details.",
                 "data": { "source": "court_availability" },
                 "sound": "default"
               }'
          
          echo "✅ Notification sent!"
        
      - name: Log completion
        run: |
          echo "=== WORKFLOW COMPLETED ==="
          echo "Completion time: $(date)"
          echo "Run ID: ${{ github.run_id }}"
          echo "Changes detected: ${{ steps.monitor.outputs.changes_detected }}"
          if [ "${{ steps.monitor.outputs.changes_detected }}" == "true" ]; then
            echo "✅ Notification sent!"
          else
            echo "✅ No changes - no notification sent"
          fi 
